import { type Metadata } from 'next'
import {
  ClerkProvider
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
<<<<<<< HEAD
import Footer from './components/footer/Footer'


=======
import { Appbar } from './components/ui/AppBar'
>>>>>>> upstream/main

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
<<<<<<< HEAD

            {children}
       
       <Footer />

=======
            <Appbar />
            {children}
          
>>>>>>> upstream/main
        </body>
      </ClerkProvider>
    </html>
  )
}